[2023-03-14T22:45:15.788+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.JsonToCSV manual__2023-03-14T22:41:08.560415+00:00 [queued]>
[2023-03-14T22:45:15.794+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.JsonToCSV manual__2023-03-14T22:41:08.560415+00:00 [queued]>
[2023-03-14T22:45:15.794+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T22:45:15.795+0000] {taskinstance.py:1280} INFO - Starting attempt 4 of 6
[2023-03-14T22:45:15.795+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T22:45:15.802+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): JsonToCSV> on 2023-03-14 22:41:08.560415+00:00
[2023-03-14T22:45:15.806+0000] {standard_task_runner.py:55} INFO - Started process 487 to run task
[2023-03-14T22:45:15.809+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'JsonToCSV', 'manual__2023-03-14T22:41:08.560415+00:00', '--job-id', '636', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmpypvdk9km']
[2023-03-14T22:45:15.810+0000] {standard_task_runner.py:83} INFO - Job 636: Subtask JsonToCSV
[2023-03-14T22:45:15.853+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.JsonToCSV manual__2023-03-14T22:41:08.560415+00:00 [running]> on host 9cebcb3c5b96
[2023-03-14T22:45:16.097+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=JsonToCSV
AIRFLOW_CTX_EXECUTION_DATE=2023-03-14T22:41:08.560415+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-14T22:41:08.560415+00:00
[2023-03-14T22:45:16.100+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/load.py", line 26, in json_to_csv
    hook=LambdaHook(conn='aws_connection',region_name='us-east-1')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/lambda_function.py", line 53, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'conn'
[2023-03-14T22:45:16.111+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=Spotify_Data_ETL, task_id=JsonToCSV, execution_date=20230314T224108, start_date=20230314T224515, end_date=20230314T224516
[2023-03-14T22:45:16.121+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 636 for task JsonToCSV (__init__() got an unexpected keyword argument 'conn'; 487)
[2023-03-14T22:45:16.145+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-14T22:45:16.166+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
