[2023-03-14T03:39:22.669+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.TestS3Hook manual__2023-03-14T00:09:25.066398+00:00 [queued]>
[2023-03-14T03:39:22.675+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.TestS3Hook manual__2023-03-14T00:09:25.066398+00:00 [queued]>
[2023-03-14T03:39:22.675+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T03:39:22.676+0000] {taskinstance.py:1280} INFO - Starting attempt 16 of 18
[2023-03-14T03:39:22.676+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T03:39:22.684+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): TestS3Hook> on 2023-03-14 00:09:25.066398+00:00
[2023-03-14T03:39:22.690+0000] {standard_task_runner.py:55} INFO - Started process 1481 to run task
[2023-03-14T03:39:22.695+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'TestS3Hook', 'manual__2023-03-14T00:09:25.066398+00:00', '--job-id', '390', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmpe7z3nyuj']
[2023-03-14T03:39:22.696+0000] {standard_task_runner.py:83} INFO - Job 390: Subtask TestS3Hook
[2023-03-14T03:39:22.746+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.TestS3Hook manual__2023-03-14T00:09:25.066398+00:00 [running]> on host c1e86c20df76
[2023-03-14T03:39:22.980+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=TestS3Hook
AIRFLOW_CTX_EXECUTION_DATE=2023-03-14T00:09:25.066398+00:00
AIRFLOW_CTX_TRY_NUMBER=16
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-14T00:09:25.066398+00:00
[2023-03-14T03:39:22.982+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/load.py", line 8, in load_tables
    json_string=json.dump(song_fact)
TypeError: dump() missing 1 required positional argument: 'fp'
[2023-03-14T03:39:22.989+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=Spotify_Data_ETL, task_id=TestS3Hook, execution_date=20230314T000925, start_date=20230314T033922, end_date=20230314T033922
[2023-03-14T03:39:22.995+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 390 for task TestS3Hook (dump() missing 1 required positional argument: 'fp'; 1481)
[2023-03-14T03:39:23.040+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-14T03:39:23.055+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
