[2023-03-21T02:58:34.585+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spotify_Data_ETL.TransformData manual__2023-03-18T04:27:11.434896+00:00 [queued]>
[2023-03-21T02:58:34.590+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spotify_Data_ETL.TransformData manual__2023-03-18T04:27:11.434896+00:00 [queued]>
[2023-03-21T02:58:34.590+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T02:58:34.591+0000] {taskinstance.py:1283} INFO - Starting attempt 9 of 11
[2023-03-21T02:58:34.591+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T02:58:34.598+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): TransformData> on 2023-03-18 04:27:11.434896+00:00
[2023-03-21T02:58:34.604+0000] {standard_task_runner.py:55} INFO - Started process 19558 to run task
[2023-03-21T02:58:34.608+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'TransformData', 'manual__2023-03-18T04:27:11.434896+00:00', '--job-id', '1682', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmpfv15lxp2']
[2023-03-21T02:58:34.609+0000] {standard_task_runner.py:83} INFO - Job 1682: Subtask TransformData
[2023-03-21T02:58:34.660+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.TransformData manual__2023-03-18T04:27:11.434896+00:00 [running]> on host 1fd7b08731f2
[2023-03-21T02:58:34.709+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=TransformData
AIRFLOW_CTX_EXECUTION_DATE=2023-03-18T04:27:11.434896+00:00
AIRFLOW_CTX_TRY_NUMBER=9
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-18T04:27:11.434896+00:00
[2023-03-21T02:58:34.748+0000] {warnings.py:110} WARNING - /opt/***/dags/src/transform.py:29: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  song_fact['date']=today

[2023-03-21T02:58:34.750+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

[2023-03-21T02:58:34.756+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/transform.py", line 39, in transform_data
    artist_dim=song_dim[['artist_name','artist_id']]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['artist_name', 'artist_id'], dtype='object')] are in the [columns]"
[2023-03-21T02:58:34.767+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=Spotify_Data_ETL, task_id=TransformData, execution_date=20230318T042711, start_date=20230321T025834, end_date=20230321T025834
[2023-03-21T02:58:34.774+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1682 for task TransformData ("None of [Index(['artist_name', 'artist_id'], dtype='object')] are in the [columns]"; 19558)
[2023-03-21T02:58:34.820+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-21T02:58:34.843+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
