[2023-03-18T03:59:42.095+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.ValidateGenre.ValidateGenre manual__2023-03-18T03:59:25.819409+00:00 [queued]>
[2023-03-18T03:59:42.112+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.ValidateGenre.ValidateGenre manual__2023-03-18T03:59:25.819409+00:00 [queued]>
[2023-03-18T03:59:42.113+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-18T03:59:42.113+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-03-18T03:59:42.114+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-18T03:59:42.129+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ValidateGenre.ValidateGenre> on 2023-03-18 03:59:25.819409+00:00
[2023-03-18T03:59:42.147+0000] {standard_task_runner.py:55} INFO - Started process 317 to run task
[2023-03-18T03:59:42.160+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'ValidateGenre.ValidateGenre', 'manual__2023-03-18T03:59:25.819409+00:00', '--job-id', '1379', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmpoi7tjawv']
[2023-03-18T03:59:42.169+0000] {standard_task_runner.py:83} INFO - Job 1379: Subtask ValidateGenre.ValidateGenre
[2023-03-18T03:59:42.276+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.ValidateGenre.ValidateGenre manual__2023-03-18T03:59:25.819409+00:00 [running]> on host d7c7ac56d661
[2023-03-18T03:59:42.431+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=ValidateGenre.ValidateGenre
AIRFLOW_CTX_EXECUTION_DATE=2023-03-18T03:59:25.819409+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-18T03:59:25.819409+00:00
[2023-03-18T03:59:42.436+0000] {logging_mixin.py:137} INFO - None
[2023-03-18T03:59:42.437+0000] {logging_mixin.py:137} INFO - ['genre']
[2023-03-18T03:59:42.437+0000] {logging_mixin.py:137} INFO - genre
[2023-03-18T03:59:42.438+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/transform.py", line 69, in validate_data
    data_table=pd.read_json(data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Unexpected character found when decoding 'NaN'
[2023-03-18T03:59:42.456+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=Spotify_Data_ETL, task_id=ValidateGenre.ValidateGenre, execution_date=20230318T035925, start_date=20230318T035942, end_date=20230318T035942
[2023-03-18T03:59:42.477+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1379 for task ValidateGenre.ValidateGenre (Unexpected character found when decoding 'NaN'; 317)
[2023-03-18T03:59:42.497+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-18T03:59:42.539+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
