[2023-03-16T04:30:49.604+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.ValidateGenre.ValidateGenre manual__2023-03-16T04:25:58.412323+00:00 [queued]>
[2023-03-16T04:30:49.614+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.ValidateGenre.ValidateGenre manual__2023-03-16T04:25:58.412323+00:00 [queued]>
[2023-03-16T04:30:49.615+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T04:30:49.615+0000] {taskinstance.py:1280} INFO - Starting attempt 5 of 5
[2023-03-16T04:30:49.616+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T04:30:49.626+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ValidateGenre.ValidateGenre> on 2023-03-16 04:25:58.412323+00:00
[2023-03-16T04:30:49.636+0000] {standard_task_runner.py:55} INFO - Started process 5711 to run task
[2023-03-16T04:30:49.653+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'ValidateGenre.ValidateGenre', 'manual__2023-03-16T04:25:58.412323+00:00', '--job-id', '1000', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmpfh5h0lka']
[2023-03-16T04:30:49.655+0000] {standard_task_runner.py:83} INFO - Job 1000: Subtask ValidateGenre.ValidateGenre
[2023-03-16T04:30:49.774+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.ValidateGenre.ValidateGenre manual__2023-03-16T04:25:58.412323+00:00 [running]> on host 18c42e4ef76b
[2023-03-16T04:30:50.084+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=ValidateGenre.ValidateGenre
AIRFLOW_CTX_EXECUTION_DATE=2023-03-16T04:25:58.412323+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-16T04:25:58.412323+00:00
[2023-03-16T04:30:50.093+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/transform.py", line 69, in validate_data
    if data_table.duplicated.any():
AttributeError: 'function' object has no attribute 'any'
[2023-03-16T04:30:50.107+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Spotify_Data_ETL, task_id=ValidateGenre.ValidateGenre, execution_date=20230316T042558, start_date=20230316T043049, end_date=20230316T043050
[2023-03-16T04:30:50.121+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1000 for task ValidateGenre.ValidateGenre ('function' object has no attribute 'any'; 5711)
[2023-03-16T04:30:50.152+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-16T04:30:50.170+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
