[2023-03-16T04:27:32.835+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.GetArtistInfo manual__2023-03-16T04:25:58.412323+00:00 [queued]>
[2023-03-16T04:27:32.840+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Spotify_Data_ETL.GetArtistInfo manual__2023-03-16T04:25:58.412323+00:00 [queued]>
[2023-03-16T04:27:32.840+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T04:27:32.841+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 3
[2023-03-16T04:27:32.841+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T04:27:32.848+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): GetArtistInfo> on 2023-03-16 04:25:58.412323+00:00
[2023-03-16T04:27:32.854+0000] {standard_task_runner.py:55} INFO - Started process 5342 to run task
[2023-03-16T04:27:32.857+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Spotify_Data_ETL', 'GetArtistInfo', 'manual__2023-03-16T04:25:58.412323+00:00', '--job-id', '957', '--raw', '--subdir', 'DAGS_FOLDER/spotifydag.py', '--cfg-path', '/tmp/tmpo68loaid']
[2023-03-16T04:27:32.858+0000] {standard_task_runner.py:83} INFO - Job 957: Subtask GetArtistInfo
[2023-03-16T04:27:32.904+0000] {task_command.py:388} INFO - Running <TaskInstance: Spotify_Data_ETL.GetArtistInfo manual__2023-03-16T04:25:58.412323+00:00 [running]> on host 18c42e4ef76b
[2023-03-16T04:27:33.069+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ananta Moharana
AIRFLOW_CTX_DAG_ID=Spotify_Data_ETL
AIRFLOW_CTX_TASK_ID=GetArtistInfo
AIRFLOW_CTX_EXECUTION_DATE=2023-03-16T04:25:58.412323+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-16T04:25:58.412323+00:00
[2023-03-16T04:27:42.995+0000] {local_task_job.py:273} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-03-16T04:27:42.998+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 5342. PIDs of all processes in the group: [5342]
[2023-03-16T04:27:42.998+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 5342
[2023-03-16T04:27:42.999+0000] {taskinstance.py:1479} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-03-16T04:27:43.007+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/extract.py", line 105, in get_artist_info
    r = requests.get(BASE_URL + 'artists/' + id, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1481, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-03-16T04:27:43.011+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=Spotify_Data_ETL, task_id=GetArtistInfo, execution_date=20230316T042558, start_date=20230316T042732, end_date=20230316T042743
[2023-03-16T04:27:43.017+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 957 for task GetArtistInfo (Task received SIGTERM signal; 5342)
[2023-03-16T04:27:43.051+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5342, status='terminated', exitcode=1, started='04:27:32') (5342) terminated with exit code 1
